Traceback (most recent call last):
  File "/hpc/home/csr33/ast_object_detection/images_for_prediction/naip_in_tracts.py", line 82, in <module>
    main(args)
  File "/hpc/home/csr33/ast_object_detection/images_for_prediction/naip_in_tracts.py", line 72, in main
    extracted_naip = extracted_naip + extract_naip_tiles_by_tract(catalog, polygon, date_range)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/home/csr33/ast_object_detection/images_for_prediction/naip_in_tracts.py", line 36, in extract_naip_tiles_by_tract
    items = search.item_collection()
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/borsuklab/cred/.conda/envs/ast-dataset/lib/python3.11/site-packages/pystac_client/item_search.py", line 765, in item_collection
    feature_collection = self.item_collection_as_dict.__wrapped__(self)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/borsuklab/cred/.conda/envs/ast-dataset/lib/python3.11/site-packages/pystac_client/item_search.py", line 786, in item_collection_as_dict
    for page in self.pages_as_dicts():
  File "/hpc/group/borsuklab/cred/.conda/envs/ast-dataset/lib/python3.11/site-packages/pystac_client/item_search.py", line 736, in pages_as_dicts
    for page in self._stac_io.get_pages(
  File "/hpc/group/borsuklab/cred/.conda/envs/ast-dataset/lib/python3.11/site-packages/pystac_client/stac_api_io.py", line 294, in get_pages
    page = self.read_json(url, method=method, parameters=parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/borsuklab/cred/.conda/envs/ast-dataset/lib/python3.11/site-packages/pystac/stac_io.py", line 205, in read_json
    txt = self.read_text(source, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/borsuklab/cred/.conda/envs/ast-dataset/lib/python3.11/site-packages/pystac_client/stac_api_io.py", line 168, in read_text
    return self.request(href, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/borsuklab/cred/.conda/envs/ast-dataset/lib/python3.11/site-packages/pystac_client/stac_api_io.py", line 217, in request
    raise APIError.from_response(resp)
pystac_client.exceptions.APIError: <!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body {font-family:Arial; margin-left:40px; }img  { border:0 none; }#content { margin-left: auto; margin-right: auto }#message h2 { font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }#message p  { font-size: 13px; color: #000000; margin: 7px 0px 0px0px}#errorref { font-size: 11px; color: #737373; margin-top: 41px }</style><title>Service unavailable</title></head><body><div id='content'><div id='message'><h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p></div><div id='errorref'><span>0Vqu7ZQAAAAD8rRROyLuxRoHSvMubXN/2U0VMMjFFREdFMDExNgA5MjdhYmZhNi0xOWY2LTRhZjEtYTA5ZC1jOTU5ZDlhMWU2NDQ=</span></div></div></body></html>
